
services:
  identityserver:
    image: fast-udap-security
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - AppConfig__SeedData=true
      - AppConfig__UdapIdpBaseUrl=https://localhost:5001
      - AppConfig__SystemAdminPassword=Password1
      - AppConfig__UdapAdminPassword=Password1
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
