version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AppConfig__UdapIdpBaseUrl=https://localhost:5001
      - AppConfig__SeedData=false
      - AppConfig__SystemAdminPassword=Password1
      - AppConfig__UdapAdminPassword=Password1
