CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

CREATE TABLE "TieredClients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientName" text NOT NULL,
    "ClientId" text NOT NULL,
    "IdPBaseUrl" text NOT NULL,
    "RedirectUri" text NOT NULL,
    "ClientUriSan" text NOT NULL,
    "CommunityId" integer NOT NULL,
    "Enabled" boolean NOT NULL,
    "TokenEndpoint" text NOT NULL,
    CONSTRAINT "PK_TieredClients" PRIMARY KEY ("Id")
);

CREATE TABLE "UdapCommunities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Enabled" boolean NOT NULL,
    "Default" boolean NOT NULL,
    CONSTRAINT "PK_UdapCommunities" PRIMARY KEY ("Id")
);

CREATE TABLE "UdapAnchors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Enabled" boolean NOT NULL,
    "Name" text NOT NULL,
    "X509Certificate" text NOT NULL,
    "Thumbprint" text NOT NULL,
    "BeginDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "CommunityId" integer NOT NULL,
    CONSTRAINT "PK_UdapAnchors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Anchor_Communities" FOREIGN KEY ("CommunityId") REFERENCES "UdapCommunities" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UdapCertifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "CommunityId" integer,
    CONSTRAINT "PK_UdapCertifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UdapCertifications_UdapCommunities_CommunityId" FOREIGN KEY ("CommunityId") REFERENCES "UdapCommunities" ("Id")
);

CREATE TABLE "UdapIntermediateCertificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnchorId" integer NOT NULL,
    "Enabled" boolean NOT NULL,
    "Name" text NOT NULL,
    "X509Certificate" text NOT NULL,
    "Thumbprint" text NOT NULL,
    "BeginDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UdapIntermediateCertificates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntermediateCertificate_Anchor" FOREIGN KEY ("AnchorId") REFERENCES "UdapAnchors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UdapAnchorCertification" (
    "AnchorId" integer NOT NULL,
    "CertificationId" integer NOT NULL,
    CONSTRAINT "PK_UdapAnchorCertification" PRIMARY KEY ("AnchorId", "CertificationId"),
    CONSTRAINT "FK_AnchorCertification_Anchor" FOREIGN KEY ("AnchorId") REFERENCES "UdapAnchors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AnchorCertification_Certification" FOREIGN KEY ("CertificationId") REFERENCES "UdapCertifications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UdapCommunityCertification" (
    "CommunityId" integer NOT NULL,
    "CertificationId" integer NOT NULL,
    CONSTRAINT "PK_UdapCommunityCertification" PRIMARY KEY ("CommunityId", "CertificationId"),
    CONSTRAINT "FK_CommunityCertification_Certification" FOREIGN KEY ("CertificationId") REFERENCES "UdapCertifications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommunityCertification_Community" FOREIGN KEY ("CommunityId") REFERENCES "UdapCommunities" ("Id")
);

CREATE INDEX "IX_UdapAnchorCertification_CertificationId" ON "UdapAnchorCertification" ("CertificationId");

CREATE INDEX "IX_UdapAnchors_CommunityId" ON "UdapAnchors" ("CommunityId");

CREATE INDEX "IX_UdapCertifications_CommunityId" ON "UdapCertifications" ("CommunityId");

CREATE INDEX "IX_UdapCommunityCertification_CertificationId" ON "UdapCommunityCertification" ("CertificationId");

CREATE INDEX "IX_UdapIntermediateCertificates_AnchorId" ON "UdapIntermediateCertificates" ("AnchorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240112011507_InitialInitialIdentityServerUdapDbMigration', '10.0.11');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240206182450_Update_Duende_v7_0InitialIdentityServerUdapDbMigration', '10.0.11');

COMMIT;

START TRANSACTION;
DROP TABLE "TieredClients";

DROP TABLE "UdapAnchorCertification";

DROP TABLE "UdapCommunityCertification";

DROP TABLE "UdapIntermediateCertificates";

DROP TABLE "UdapCertifications";

DROP TABLE "UdapAnchors";

DROP TABLE "UdapCommunities";

ALTER TABLE "DataProtectionKeys" DROP CONSTRAINT "PK_DataProtectionKeys";

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'udap') THEN
        CREATE SCHEMA udap;
    END IF;
END $EF$;

ALTER TABLE "DataProtectionKeys" RENAME TO data_protection_keys;
ALTER TABLE data_protection_keys SET SCHEMA udap;

ALTER TABLE udap.data_protection_keys RENAME COLUMN "Xml" TO xml;

ALTER TABLE udap.data_protection_keys RENAME COLUMN "Id" TO id;

ALTER TABLE udap.data_protection_keys RENAME COLUMN "FriendlyName" TO friendly_name;

ALTER TABLE udap.data_protection_keys ADD CONSTRAINT pk_data_protection_keys PRIMARY KEY (id);

CREATE TABLE udap.tiered_clients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    client_name text NOT NULL,
    client_id text NOT NULL,
    id_pbase_url text NOT NULL,
    redirect_uri text NOT NULL,
    client_uri_san text NOT NULL,
    community_id integer NOT NULL,
    enabled boolean NOT NULL,
    token_endpoint text NOT NULL,
    CONSTRAINT pk_tiered_clients PRIMARY KEY (id)
);

CREATE TABLE udap.udap_communities (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    enabled boolean NOT NULL,
    "default" boolean NOT NULL,
    CONSTRAINT pk_udap_communities PRIMARY KEY (id)
);

CREATE TABLE udap.udap_anchors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    enabled boolean NOT NULL,
    name text NOT NULL,
    x509_certificate text NOT NULL,
    thumbprint text NOT NULL,
    begin_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    community_id integer NOT NULL,
    CONSTRAINT pk_udap_anchors PRIMARY KEY (id),
    CONSTRAINT fk_anchor_communities FOREIGN KEY (community_id) REFERENCES udap.udap_communities (id) ON DELETE CASCADE
);

CREATE TABLE udap.udap_certifications (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    community_id integer,
    CONSTRAINT pk_udap_certifications PRIMARY KEY (id),
    CONSTRAINT fk_udap_certifications_udap_communities_community_id FOREIGN KEY (community_id) REFERENCES udap.udap_communities (id)
);

CREATE TABLE udap.udap_intermediate_certificates (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    anchor_id integer NOT NULL,
    enabled boolean NOT NULL,
    name text NOT NULL,
    x509_certificate text NOT NULL,
    thumbprint text NOT NULL,
    begin_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_udap_intermediate_certificates PRIMARY KEY (id),
    CONSTRAINT fk_intermediate_certificate_anchor FOREIGN KEY (anchor_id) REFERENCES udap.udap_anchors (id) ON DELETE CASCADE
);

CREATE TABLE udap.udap_anchor_certification (
    anchor_id integer NOT NULL,
    certification_id integer NOT NULL,
    CONSTRAINT pk_udap_anchor_certification PRIMARY KEY (anchor_id, certification_id),
    CONSTRAINT fk_anchor_certification_anchor FOREIGN KEY (anchor_id) REFERENCES udap.udap_anchors (id) ON DELETE CASCADE,
    CONSTRAINT fk_anchor_certification_certification FOREIGN KEY (certification_id) REFERENCES udap.udap_certifications (id) ON DELETE CASCADE
);

CREATE TABLE udap.udap_community_certification (
    community_id integer NOT NULL,
    certification_id integer NOT NULL,
    CONSTRAINT pk_udap_community_certification PRIMARY KEY (community_id, certification_id),
    CONSTRAINT fk_community_certification_certification FOREIGN KEY (certification_id) REFERENCES udap.udap_certifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_community_certification_community FOREIGN KEY (community_id) REFERENCES udap.udap_communities (id)
);

CREATE INDEX ix_udap_anchor_certification_certification_id ON udap.udap_anchor_certification (certification_id);

CREATE INDEX ix_udap_anchors_community_id ON udap.udap_anchors (community_id);

CREATE INDEX ix_udap_certifications_community_id ON udap.udap_certifications (community_id);

CREATE INDEX ix_udap_community_certification_certification_id ON udap.udap_community_certification (certification_id);

CREATE INDEX ix_udap_intermediate_certificates_anchor_id ON udap.udap_intermediate_certificates (anchor_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820163545_Update_Duende_v8_0InitialIdentityServerUdapDbMigration', '10.0.11');

COMMIT;

